version: '2'
services:

  db:
    image: mariadb:10.3.2
    container_name: datalink_mariadb
    restart: always
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=datalink
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=dinsorsee

  php:
    build: ./
    # image: php:5.6
    container_name: datalink_phpfpm
    restart: always
    volumes:
      - ./www/:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: datalink_nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    volumes_from:
      - php
    ports:
      - 80:80
      
  pma:
      image: phpmyadmin/phpmyadmin
      container_name: datalink-phpmyadmin
      restart: always
      ports:
        - "8000:80"
